/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as IndustriesSlugRouteImport } from './routes/industries.$slug'
import { Route as CaseStudiesSlugRouteImport } from './routes/case-studies.$slug'
import { Route as CareersJobIdRouteImport } from './routes/careers.$jobId'

const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesSlugRoute = IndustriesSlugRouteImport.update({
  id: '/industries/$slug',
  path: '/industries/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesSlugRoute = CaseStudiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CaseStudiesRoute,
} as any)
const CareersJobIdRoute = CareersJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => CareersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/careers': typeof CareersRouteWithChildren
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/careers/$jobId': typeof CareersJobIdRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/careers': typeof CareersRouteWithChildren
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/careers/$jobId': typeof CareersJobIdRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/careers': typeof CareersRouteWithChildren
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/careers/$jobId': typeof CareersJobIdRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/careers'
    | '/case-studies'
    | '/careers/$jobId'
    | '/case-studies/$slug'
    | '/industries/$slug'
    | '/services/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/careers'
    | '/case-studies'
    | '/careers/$jobId'
    | '/case-studies/$slug'
    | '/industries/$slug'
    | '/services/$slug'
  id:
    | '__root__'
    | '/'
    | '/careers'
    | '/case-studies'
    | '/careers/$jobId'
    | '/case-studies/$slug'
    | '/industries/$slug'
    | '/services/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CareersRoute: typeof CareersRouteWithChildren
  CaseStudiesRoute: typeof CaseStudiesRouteWithChildren
  IndustriesSlugRoute: typeof IndustriesSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/$slug': {
      id: '/industries/$slug'
      path: '/industries/$slug'
      fullPath: '/industries/$slug'
      preLoaderRoute: typeof IndustriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/$slug': {
      id: '/case-studies/$slug'
      path: '/$slug'
      fullPath: '/case-studies/$slug'
      preLoaderRoute: typeof CaseStudiesSlugRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/careers/$jobId': {
      id: '/careers/$jobId'
      path: '/$jobId'
      fullPath: '/careers/$jobId'
      preLoaderRoute: typeof CareersJobIdRouteImport
      parentRoute: typeof CareersRoute
    }
  }
}

interface CareersRouteChildren {
  CareersJobIdRoute: typeof CareersJobIdRoute
}

const CareersRouteChildren: CareersRouteChildren = {
  CareersJobIdRoute: CareersJobIdRoute,
}

const CareersRouteWithChildren =
  CareersRoute._addFileChildren(CareersRouteChildren)

interface CaseStudiesRouteChildren {
  CaseStudiesSlugRoute: typeof CaseStudiesSlugRoute
}

const CaseStudiesRouteChildren: CaseStudiesRouteChildren = {
  CaseStudiesSlugRoute: CaseStudiesSlugRoute,
}

const CaseStudiesRouteWithChildren = CaseStudiesRoute._addFileChildren(
  CaseStudiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CareersRoute: CareersRouteWithChildren,
  CaseStudiesRoute: CaseStudiesRouteWithChildren,
  IndustriesSlugRoute: IndustriesSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
